### ISSUE TITLE
How can we deal with flow files in dependencies?

### ISSUE THREAD

**Issue by sbalay** [onejs/one#13]
Hey @natew 👋 

I was trying `vxrn` in one of my projects and saw the following error:

```
[commonjs--resolver] Unexpected token (15:12) in /Users/sebastianbalay/src/github.com/Shopify/shop-client/node_modules/@react-native-community/push-notification-ios/js/index.js
file: /Users/sebastianbalay/src/github.com/Shopify/shop-client/node_modules/@react-native-community/push-notification-ios/js/index.js:15:12
13: import {NativeEventEmitter, NativeModules} from 'react-native';
14: import invariant from 'invariant';
15: import type {
                ^
16:   NotificationAlert,
17:   NotificationRequest,
```

I guess the error makes sense since the file is actually written in [flow](https://flow.org/). Does `vxrn` support imports from these files?

**Comment by natew** [comment]
You’d need to configure vite plugin flow for that dependency. But I’d like to make vxrn automatically do this, so we can make a PR that configured that out of the box. We should also very strongly suggest pester that library to fix it, it’s a terrible practice to publish flow directly.
