### ISSUE TITLE
Minimal template missing vite dependency in package.json

### ISSUE THREAD

**Issue by israataha** [onejs/one#132]
Following the [Installation documentation](https://onestack.dev/docs/installation)  I ran `npx one` and selected the `Minimal` template.

Running the project with `npm run dev` gives the following error: 

>  ERROR  Cannot find package 'vite' imported from [project_folder]/node_modules/@vxrn/vite-flow/dist/esm/index.mjs

The `vite` dependency is missing from the [template's package.json file](https://github.com/onejs/one/blob/main/examples/one-basic/package.json)

```
{
  "name": "example-basic",
  "version": "1.1.297",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "one dev",
    "dev:clean": "one dev --clean",
    "clean": "one clean",
    "prebuild:native": "one prebuild",
    "build:web": "one build",
    "serve": "one serve"
  },
  "installConfig": {
    "hoistingLimits": "workspaces"
  },
  "dependencies": {
    "expo": "~51.0.28",
    "one": "1.1.297",
    "react": "^18.3.1",
    "react-native": "0.74.1",
    "react-native-web": "^0.19.12"
  }
}
```

**Comment by natew** [comment]
Thanks, fixed that.
