### ISSUE TITLE
Minimal example fails to build in native simulator

### ISSUE THREAD

**Issue by ceopaludetto** [onejs/one#133]
Reproducible steps:

1. `bunx one`
2. Select the minimal example
3. Run `bun prebuild:native`
3. Run `bun ios`
4. Run `bun run dev`

When I reload the simulator, I get this error:
![Simulator Screenshot - iPhone 16 Pro - 2024-10-07 at 09 39 32](https://github.com/user-attachments/assets/994511a6-df45-4a8f-905e-72c4374efbb0)

**Comment by ceopaludetto** [comment]
I've tried to install `react-native-safe-area-context` with `bun expo install react-native-safe-area-context`

**Comment by zetavg** [comment]
Hi @ceopaludetto, thanks for reporting. We'll update our templates to include the missing deps.

For your situation for now - seems that `react-native-screens` might also be needed as well, could you try:

```bash
bun expo install react-native-screens react-native-safe-area-context
```

And after installing, run:

```bash
cd ios && pod install
```

 would be needed for the iOS project to pickup newly added deps. Then re-run `ios` and that error may go away.
