### ISSUE TITLE
Do you have a roadmap or milestones?

### ISSUE THREAD

**Issue by sunrabbit123** [onejs/one#14]
hello!

This library seems to be in a very early stage.

Do you happen to have any milestones or roadmap for contributors?

**Comment by natew** [comment]
That's the next step, I'll be looking at that soon. Any suggestions welcome for organizing that, not sure if Projects or Issues or just a readme with bullet points is best.

**Comment by sunrabbit123** [comment]
I think it would be nice to have both.

Only the biggest chunks in the README,

issue and milestone to write the details and tie in with PR.
