### ISSUE TITLE
Access hono context from api

### ISSUE THREAD

**Issue by clayrisser** [onejs/one#140]
How can I access the hono context from an api endpoint I create in this framework?

**Comment by jonsherrard** [comment]
Hey @clayrisser,

I like where this is going!

Could you explain a bit more about what you're trying to do. Currently we use a different framework in dev and prod, so this might not work as expected if we just expose the context.

**Comment by clayrisser** [comment]
I'm trying to get auth-js working.

https://authjs.dev

**Comment by clayrisser** [comment]
I was able to work around this and get authjs almost working, but the following issue is preventing the authentication cookie from getting set.

https://github.com/onejs/one/issues/156

**Comment by clayrisser** [comment]
authjs is working now
