### ISSUE TITLE
Logo in the Footer Does Not Link to the Homepage

### ISSUE THREAD

**Issue by Asin-Junior-Honore** [onejs/one#142]
I noticed that when scrolling to the footer, the logo icon does not link back to the homepage or the top of the page as expected. Typically, users would expect the logo to serve as a shortcut to navigate back to the top or the homepage, but this functionality seems to be missing.

Could we add this behavior to improve user experience?

**Comment by Asin-Junior-Honore** [comment]
Hey @natew 👋,

Could this issue be assigned to me? I’d love to take on the task of implementing this feature! 🚀

Thanks!

**Comment by natew** [comment]
Oh yea good callout, let's do that, should be pretty straightforward gl!

**Comment by Asin-Junior-Honore** [comment]
Hey @natew 👋,

I noticed  the issue on the [https://onestack.dev/] site and wanted to dive in to help. Could you please point me to the directory where the code for this site is located? I’ve gone through the files and directories in the forked repo I have but couldn’t seem to find the entry point.

Thanks in advance! 🙏

**Comment by jonsherrard** [comment]
ah sorry @Asin-Junior-Honore, I just fixed this.

The docs are in `code/ooo` in https://github.com/tamagui/tamagui in the future.
