### ISSUE TITLE
Feat : Add 404 Not Found Page

### ISSUE THREAD

**Issue by vinaysanwal** [onejs/one#144]
Create a 404 Not Found Page 

@jonsherrard  I would like to contribute by creating one 

Page Design : 

<img width="750" alt="Screenshot 2024-10-08 at 8 28 28 AM" src="https://github.com/user-attachments/assets/5e191850-7b9b-490d-a933-b336a65a6883">

**Comment by jonsherrard** [comment]
Thank you for the suggestion, `+not-found` routes are coming very soon 👀
