### ISSUE TITLE
request to open a community communication channel (e.g., discord)

### ISSUE THREAD

**Issue by minai621** [onejs/one#180]
I'm a developer interested in contributing to this project. It would be useful to have a community communication channel, like Discord, to discuss development-related topics, exchange ideas, and get real-time feedback.

Please consider opening a channel for better collaboration.

Thanks.

**Comment by natew** [comment]
We actually have a discord but it's only showing on desktop layout on the site and its just an icon, we need to make that much better. 

https://discord.gg/JmjdA9gb

I'll get that more prominent soon.
