### ISSUE TITLE
Generated app version controls generated ./app/tamagui.css

### ISSUE THREAD

**Issue by pandeiro** [onejs/one#222]
New to Tamagui, but generally files that are tooling-generated get gitignored to avoid the source and target becoming out of sync, or changes to the target being erased the next time the tool generates from source.

Is the way that the example is setup intentional? If so, maybe an explanatory note somewhere would help. As it is, it's unclear if I should be making direct edits to `app/tamagui.css` or only working within `config/tamagui.config.ts`

**Comment by natew** [comment]
We could ignore `app/tamagui.css` as it is auto-generated, adding a comment at the top would be good for tamagui to do. I'll note that for a future release.

**Comment by natew** [comment]
fixed in 29c712b84fdfac756a5e794118d68914baaf0486
