### ISSUE TITLE
Updated to latest (1.1.324 -> 1.1.330) and see babel errors

### ISSUE THREAD

**Issue by canadaduane** [onejs/one#238]
After updating to latest version of One (1.1.330) I now see the following errors when trying to `bun dev`:

```
✘ [ERROR] Could not resolve "@babel/runtime/helpers/interopRequireDefault"

    ../.bun/install/cache/react-native-web@0.19.13@@@1/dist/cjs/exports/SafeAreaView/index.js:3:37:
      3 │ var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;
        ╵                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@babel/runtime/helpers/interopRequireDefault" as external to exclude it
  from the bundle, which will remove this error and leave the unresolved path in the bundle. You can
  also surround this "require" call with a try/catch block to handle this failure at run-time
  instead of bundle-time.
```

There are hundreds of similar lines, e.g. exports/YellowBox/index.js, exports/Text/index.js etc.

**Comment by zetavg** [comment]
Thanks for reporting! I'd tried with `npx one`, selecting the `Minimal Tamagui` template and `bun`, starting the dev server with `bun dev`, but I couldn’t reproduce the issue on either web or native.

Could you provide your `package.json` or try creating a minimal reproduction of the problem to help us investigate further?

**Comment by canadaduane** [comment]
I will hopefully have time to check again this weekend. Thanks for your patience.
