### ISSUE TITLE
Tabs nav is broken

### ISSUE THREAD

**Issue by affectful** [onejs/one#249]
On today's (not sure when it started) `npx one` starter the tabs are broken. When switching tabs it stays on the last rendered page.

I followed the onestack guide and it works fine on the expo starter.

Let me know if you need a repro repo.

<img width="419" alt="Screenshot 2024-11-22 at 5 02 29 PM" src="https://github.com/user-attachments/assets/4829f01a-a9c8-40d8-ae26-522bf614f841">
<img width="239" alt="Screenshot 2024-11-22 at 5 02 34 PM" src="https://github.com/user-attachments/assets/f1b50786-bdd1-4a91-93e2-f9ccc0c2fb3d">

**Comment by TomGillen** [comment]
It works if you explicitly set the `href` option:

```html
<Tabs.Screen
  name="explore"
  options={{
    title: 'Explore',
    href: '/explore',
  }}
/>
```

**Comment by affectful** [comment]
Either a documentation problem or API needs to be updated to be compatible/similar to expo-router then

**Comment by natew** [comment]
I've added docs here, sorry that took so long. Added a todo to make this automatic.
