### ISSUE TITLE
Wildcard routes

### ISSUE THREAD

**Issue by prabirshrestha** [onejs/one#257]
I'm creating a file explorer and would like to know how to create a wildcard route. [Navigation docs](https://onestack.dev/docs/routing-navigation) explicitly only mentions a single sub path.

I would want to match `/files/*path` where `*path` can be `/a` or `/a/b` with any nesting of levels. 

Since I want to optimize if it is a directory or a file, does one router differentiate between `/a/` and `/a` (note the trailing `/`).

**Comment by natew** [comment]
You would use rest parameter routes:

https://onestack.dev/docs/routing#rest-parameter-routes
