### ISSUE TITLE
Incompatible with asdf

### ISSUE THREAD

**Issue by clayrisser** [onejs/one#295]
This is incompatible with asdf.

https://github.com/asdf-vm/asdf
https://github.com/asdf-vm/asdf-nodejs

I get the following error when using asdf.

```
No preset version installed for command node
Please install a version by running one of the following:

asdf install nodejs 20.11

or add one of the following versions in your config file at /home/clayrisser/.tool-versions
nodejs 20.18.0
nodejs 23.1.0
```

**Comment by clayrisser** [comment]
It seems the issue is because the node version needs to also include the patch version.

**Comment by zetavg** [comment]
Thanks for the update! I’m also using [asdf](https://github.com/asdf-vm/asdf).

Just a quick tip for handling situations like this - I’ve encountered similar issues before (e.g., an incomplete version number in .node-version, which some other VMs tolerate I think). You can use [asdf-alias](https://github.com/andrewthauer/asdf-alias) to resolve it:

```bash
asdf alias nodejs 20.11 20.11.1
```

This command creates an alias for 20.11 that points to 20.11.1, so the version 20.11 specified in .node-version will map to 20.11.1 without needing to modify the repository.

Under the hood, this actually creates a symbolic link in the file system:

```bash
$ ls -al ~/.asdf/installs/nodejs/
total 16
drwxr-xr-x  30 z  staff   960 Dec 12 21:46 .
drwxr-xr-x   5 z  staff   160 Sep 12 19:37 ..
lrwxr-xr-x   1 z  staff     7 Jun 10  2024 20.11 -> 20.11.1
drwxr-xr-x  10 z  staff   320 Sep 12  2023 20.11.1
...
```

I believe the same can be achieved by manually creating a soft link without using asdf-alias.
