### ISSUE TITLE
Cannot import @lexical/react

### ISSUE THREAD

**Issue by tazsingh** [onejs/one#303]
When installing `@lexical/react`, I get the following error:

```
ERROR  Failed to resolve entry for package "@lexical/react". The package may have incorrect main/module/exports specified in its package.json: Missing "." specifier in "@lexical/react" package
```

I believe `autoPreBundleDepsForSsrPlugin` is trying to bundle specifically `@lexical/react` (and not a sub-export) within Vite, which doesn't specify a top-level barrel file for its exports, and is failing.

To replicate:

1. Create a new One project
2. Install `@lexical/react`
3. Run the `dev` command

**Comment by natew** [comment]
Fix in 8aee80e2e5e82edd612c7a4819c1e18fdad843c4, cutting release now
