### ISSUE TITLE
Dependency Version Conflicts in Minimal Tamagui Template

### ISSUE THREAD

**Issue by vastava** [onejs/one#307]
I used the `npx one` command to create a new hello-world app, but I encountered version conflicts when running npm install. Using the CLI, I selected npm as package manager and "Minimal Tamagui" as the template.

I got an error because the template is using react@^18.3.1, but react-native@0.74.5 has a peer dependency of react@18.2.0. 

Steps to reproduce:

Run npx one to create a new app with the "Minimal Tamagui" template.
Choose npm as the package manager.
Run npm install.

Expected behavior:

The dependencies should be compatible with each other, and npm install should complete without errors or warnings.
Actual behavior:

npm install fails due to conflicting versions, particularly for React and Vite, and results in multiple warnings.

Would you be able to update the template to ensure all dependencies are compatible?

**Comment by zetavg** [comment]
It seems like a warning but not an error, and things will be fine. But anyway, let's try to get rid of those.

```
✔ Package Manager: › npm


Installing with npm...

npm warn using --force Recommended protections disabled.
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: react-native@0.74.5
npm warn Found: react@18.3.1
npm warn node_modules/react
npm warn   react@"^18.3.1" from the root project
npm warn   40 more (@react-native-masked-view/masked-view, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer react@"18.2.0" from react-native@0.74.5
npm warn node_modules/react-native
npm warn   react-native@"0.74.5" from the root project
npm warn   16 more (@react-native-masked-view/masked-view, ...)
npm warn
npm warn Conflicting peer dependency: react@18.2.0
npm warn node_modules/react
npm warn   peer react@"18.2.0" from react-native@0.74.5
npm warn   node_modules/react-native
npm warn     react-native@"0.74.5" from the root project
npm warn     16 more (@react-native-masked-view/masked-view, ...)
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @vitejs/plugin-react-swc@3.7.2
npm warn Found: vite@6.0.0-beta.1
npm warn node_modules/vite
npm warn   dev vite@"6.0.0-beta.1" from the root project
npm warn   4 more (@tamagui/vite-plugin, one, vite-tsconfig-paths, vxrn)
npm warn
npm warn Could not resolve dependency:
npm warn peer vite@"^4 || ^5 || ^6" from @vitejs/plugin-react-swc@3.7.2
npm warn node_modules/@vitejs/plugin-react-swc
npm warn   @vitejs/plugin-react-swc@"^3.7.0" from vxrn@1.1.342
npm warn   node_modules/vxrn
npm warn
npm warn Conflicting peer dependency: vite@6.0.3
npm warn node_modules/vite
npm warn   peer vite@"^4 || ^5 || ^6" from @vitejs/plugin-react-swc@3.7.2
npm warn   node_modules/@vitejs/plugin-react-swc
npm warn     @vitejs/plugin-react-swc@"^3.7.0" from vxrn@1.1.342
npm warn     node_modules/vxrn
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: vite-plugin-mkcert@1.17.6
npm warn Found: vite@6.0.0-beta.1
npm warn node_modules/vite
npm warn   dev vite@"6.0.0-beta.1" from the root project
npm warn   4 more (@tamagui/vite-plugin, one, vite-tsconfig-paths, vxrn)
npm warn
npm warn Could not resolve dependency:
npm warn peer vite@">=3" from vite-plugin-mkcert@1.17.6
npm warn node_modules/vite-plugin-mkcert
npm warn   vite-plugin-mkcert@"^1.17.5" from vxrn@1.1.342
npm warn   node_modules/vxrn
npm warn
npm warn Conflicting peer dependency: vite@6.0.3
npm warn node_modules/vite
npm warn   peer vite@">=3" from vite-plugin-mkcert@1.17.6
npm warn   node_modules/vite-plugin-mkcert
npm warn     vite-plugin-mkcert@"^1.17.5" from vxrn@1.1.342
npm warn     node_modules/vxrn
```

**Comment by vastava** [comment]
Right, but when building the project I see several build errors from the dependencies not resolving correctly

`> hello-world@1.1.342 dev
> one dev

 🩹 Patching react
 🩹 Patching react
 🩹 Patching @react-native/assets-registry
 🩹 Patching whatwg-url-without-unicode
 🩹 Patching @hono/node-server
 🩹 Patching @hono/node-server
 🩹 Patching whatwg-url-without-unicode
 🩹 Patching @react-native/assets-registry
 🩹 Patching @react-native-masked-view/masked-view
 🩹 Patching @react-native-masked-view/masked-view
 🩹 Patching expo
 🩹 Patching @expo/vector-icons
 🩹 Patching @expo/vector-icons
 🩹 Patching rollup
 🩹 Patching rollup
 🩹 Patching react-dom
 🩹 Patching @react-native-community/cli-config
 🩹 Patching react-dom

    ➡ [tamagui] built config and components (1229ms)
[vite] connected.
Cannot optimize dependency: url-parse, present in ssr 'optimizeDeps.include'
Cannot optimize dependency: query-string, present in ssr 'optimizeDeps.include'
Cannot optimize dependency: moti/author, present in ssr 'optimizeDeps.include'
Cannot optimize dependency: react-native, present in ssr 'optimizeDeps.include'
Cannot optimize dependency: @expo/cli, present in ssr 'optimizeDeps.include'
Cannot optimize dependency: react-native-safe-area-context, present in ssr 'optimizeDeps.include'
Cannot optimize dependency: react-native, present in ssr 'optimizeDeps.include'
✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/react-native-web

    node_modules/@floating-ui/react-native/dist/floating-ui.react-native.esm.js:4:48:
      4 │ import { Platform, Dimensions, StatusBar } from 'react-native';
        ╵                                                 ~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/tslib-lite

    node_modules/react-remove-scroll/dist/es2015/Combination.js:1:25:
      1 │ import { __assign } from "tslib";
        ╵                          ~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/safe-area

    node_modules/@react-navigation/drawer/lib/module/views/DrawerContentScrollView.js:4:34:
      4 │ import { useSafeAreaInsets } from 'react-native-safe-area-context';
        ╵                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/query-string

    node_modules/@react-navigation/core/lib/module/getPathFromState.js:1:29:
      1 │ import * as queryString from 'query-string';
        ╵                              ~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/url-parse

    node_modules/one/dist/esm/fork/extractPathFromURL.mjs:1:16:
      1 │ import URL from "url-parse";
        ╵                 ~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/react-native-web

    node_modules/react-native-screens/lib/module/core.js:1:36:
      1 │ import { Platform, UIManager } from 'react-native';
        ╵                                     ~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/safe-area

    node_modules/one/dist/esm/index.mjs:10:29:
      10 │ import { SafeAreaView } from "react-native-safe-area-context";
         ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/query-string

    node_modules/@react-navigation/core/lib/module/getPathFromState.js:1:29:
      1 │ import * as queryString from 'query-string';
        ╵                              ~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/url-parse

    node_modules/one/dist/esm/fork/extractPathFromURL.mjs:1:16:
      1 │ import URL from "url-parse";
        ╵                 ~~~~~~~~~~~

✘ [ERROR] Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/tslib-lite

    node_modules/react-remove-scroll/dist/es2015/Combination.js:1:25:
      1 │ import { __assign } from "tslib";
        ╵                          ~~~~~~~


 ERROR  Build failed with 5 errors:                                
node_modules/@floating-ui/react-native/dist/floating-ui.react-native.esm.js:4:48: ERROR: Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/react-native-web
node_modules/@react-navigation/core/lib/module/getPathFromState.js:1:29: ERROR: Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/query-string
node_modules/@react-navigation/drawer/lib/module/views/DrawerContentScrollView.js:4:34: ERROR: Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/safe-area
node_modules/one/dist/esm/fork/extractPathFromURL.mjs:1:16: ERROR: Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/url-parse
node_modules/react-remove-scroll/dist/es2015/Combination.js:1:25: ERROR: Could not read from file: <PROJECT_ROOT>/node_modules/@vxrn/resolve/dist/esm/@vxrn/tslib-lite

  node_modules/@floating-ui/react-native/dist/floating-ui.react-native.esm.js:4:48: ERROR: Could not read from file: node_modules/@vxrn/resolve/dist/esm/react-native-web
  node_modules/@react-navigation/core/lib/module/getPathFromState.js:1:29: ERROR: Could not read from file: node_modules/@vxrn/resolve/dist/esm/@vxrn/query-string
  node_modules/@react-navigation/drawer/lib/module/views/DrawerContentScrollView.js:4:34: ERROR: Could not read from file: node_modules/@vxrn/resolve/dist/esm/@vxrn/safe-area
  node_modules/one/dist/esm/fork/extractPathFromURL.mjs:1:16: ERROR: Could not read from file: node_modules/@vxrn/resolve/dist/esm/@vxrn/url-parse
  node_modules/react-remove-scroll/dist/es2015/Combination.js:1:25: ERROR: Could not read from file: node_modules/@vxrn/resolve/dist/esm/@vxrn/tslib-lite
  at failureErrorWithLog (node_modules/vite/node_modules/esbuild/lib/main.js:1472:15)
  at node_modules/vite/node_modules/esbuild/lib/main.js:945:25
  at node_modules/vite/node_modules/esbuild/lib/main.js:1353:9
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
`

**Comment by zetavg** [comment]
I do not see that one on my side. Would you be able to create a reproduce repo?

![](https://github.com/user-attachments/assets/916c7c34-04d9-4618-98be-c8762b5d9464)

**Comment by vastava** [comment]
I was running an older version of npm (8.19.3)
Updated to latest and able to build with no issues!
